import Head from 'next/head'
import NavBar from '../components/NavBar/'

import ShoppingCart from '../components/ShoppingCart/index.js'

export default function Cart() {
  return (
    <>
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <h1 className="header">Shopping Cart</h1>
      <ShoppingCart/>

      
      
    </>
  )
}