import Head from 'next/head'

//import edit user component
import EditUser from '../components/EditUser/index.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditUser />
    </>
  )
}