import Head from 'next/head'
import NavBar from '../components/NavBar/'
import EditItem from '../components/EditItem/'

export default function Home() {
  return (
    <>
      <Head>
        <title>Item</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <h1 className="header">Edit Item</h1>
      <EditItem/>
    </>
  )
}