import Head from 'next/head'
import { useContext } from "react";
import { UserContext } from "../contexts/UserContext";

//import login component
import LoginPage from '../components/LoginPage/index.js'

export default function Login() {

  const { user, setUser } = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </>
  )
}