import Head from 'next/head'

//import register component
import RegisterUser from '../components/RegisterUser/index.js'

export default function Register() {

  async function handleCreate(event) {

  }

  return (
    <>
      <Head>
        <title>Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterUser />
    </>
  )
}