import Head from 'next/head'
import NavBar from '../components/NavBar/'

//import create listing component
import CreateListing from '../components/CreateListing/index.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sell Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <CreateListing/>
    </>
  )
}