import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router'
import { useContext, useEffect } from "react";
import { UserContext } from "../contexts/UserContext";

import NavBar from '../components/NavBar/'
import ViewListings from '../components/ViewListings/user';

export default function User() {

  const { user, setUser } = useContext(UserContext);
  const router = useRouter();

  useEffect(() => {
    if (!user.token) {
      router.push('/login/');
    }
  }, []);

  return (
    <>
      <Head>
        <title>User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <h1><Link href="/edituser" className="header">User Profile</Link></h1>

      <h3 className="header">Your Listings</h3>
      <ViewListings />
    </>
  )
}